# 开发环境配置

app:
  name: gin-center
  env: dev
  port: 8080
  logLevel: debug
  version: 2.1.0
  host: localhost

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: 123456
  dbName: gin_center
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 100

log:
  level: debug
  filename: ./logs/app.log
  max_size: 100
  max_age: 7
  max_backups: 10
  compress: true
  request:
    skip_paths: ["/health", "/metrics"]
    max_body_size: 1048576
    log_headers: true
    log_body: true
    log_response: true
    sensitive_log: false
  trace:
    enabled: true
    header_name: "X-Trace-ID"

server:
  port: 8080

jwt:
  secret: anysg_secret
  expire: 24h
  issuer: gin-center
  RefreshWindow: 12h

rate_limit:
  enable: true
  requests: 100
  duration: 60