# 开发环境配置

app:
  name: gin-center
  version: 2.1.0
  mode: dev
  port: 8080

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: 123456
  database: gin_center
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 100

log:
  level: debug
  path: h:/Project/gin-center/logs
  filename: h:/Project/gin-center/logs/app.log
  max_size: 100
  max_age: 7
  max_backups: 10

server:
  port: 8080

jwt:
  secret: anysg_secret
  expire: 24h
  issuer: gin-center
  refresh_threshold: 0.5
  refresh_window: 12h

rate_limit:
  enable: true
  requests: 100
  duration: 60