# 生产环境配置

app:
  name: gin-center
  env: production
  port: 8080
  logLevel: info

database:
  driver: mysql
  host: ${DB_HOST}
  port: ${DB_PORT}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  dbName: gin_center
  charset: utf8mb4
  parse_time: true
  loc: Local
  charset: utf8mb4
  parse_time: true
  loc: Local
  max_idle_conns: 10
  max_open_conns: 200
  conn_max_lifetime: 3600

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  db: 0
  pool_size: 200
  min_idle_conns: 10
  max_conn_age: 300s
  idle_timeout: 60s
  wait: true
  max_retries: 3

log:
  level: info
  filename: /var/log/gin-center/app.log
  max_size: 100
  max_age: 30
  max_backups: 30

jwt:
  secret: ${JWT_SECRET}
  expire_hours: 12

rate_limit:
  enable: true
  requests: 50
  duration: 60